# Generated by Django 3.2.4 on 2021-08-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated',
        ),
    ]
